# Structurelint Configuration for LangPlug
# Enforces project structure, organization, and architectural integrity
# See: https://github.com/Jonathangadeaharder/structurelint

root: true

# Global rules for all directories
rules:
  # Maximum folder depth to prevent over-nesting
  # Aligned with project standard: max depth of 6-7
  max-depth: { max: 7 }

  # Maximum files per directory to maintain organization
  max-files-in-dir: { max: 20 }

  # Maximum subdirectories per directory
  max-subdirs: { max: 15 }

  # Disallow version suffixes (enforces "NO VERSION SUFFIXES IN CODE" rule)
  disallowed-patterns:
    - pattern: ".*_(v[0-9]+|new|old|temp|backup|copy)\\.(py|ts|tsx|js|jsx)$"
      message: "Version suffixes (_v2, _new, _old, _temp, _backup) are forbidden. Use git for versioning."
    - pattern: ".*_(v[0-9]+|new|old|temp|backup|copy)/$"
      message: "Version suffixes in directory names are forbidden. Use git for versioning."

  # Require essential project documentation files
  file-existence:
    "CLAUDE.md": "exists:1"
    "README.md": "exists:1"
    ".gitignore": "exists:1"

# Python Backend Rules
overrides:
  # Backend: Python files and directories use snake_case
  - files: ['src/backend/**']
    rules:
      max-depth: { max: 7 }
      max-files-in-dir: { max: 25 }

      naming-convention:
        "*.py": "snake_case"
        "**/": "snake_case"

      # Backend services should have __init__.py
      file-existence:
        "__init__.py": "exists:1"

  # Backend services: Stricter organization
  - files: ['src/backend/services/**']
    rules:
      max-files-in-dir: { max: 15 }
      max-subdirs: { max: 10 }

  # Backend tests: Mirror source structure
  - files: ['src/backend/tests/**']
    rules:
      max-depth: { max: 8 }
      max-files-in-dir: { max: 30 }

      naming-convention:
        "*.py": "snake_case"
        "**/": "snake_case"

  # TypeScript/React Frontend Rules
  - files: ['src/frontend/**']
    rules:
      max-depth: { max: 7 }
      max-files-in-dir: { max: 20 }

      naming-convention:
        # Files use kebab-case
        "*.ts": "kebab-case"
        "*.js": "kebab-case"
        "**/": "kebab-case"

  # React components can use PascalCase
  - files: ['src/frontend/src/components/**', 'src/frontend/src/screens/**', 'src/frontend/src/contexts/**']
    rules:
      naming-convention:
        "*.tsx": "PascalCase"
        "*.jsx": "PascalCase"

  # Scripts: Use snake_case
  - files: ['scripts/**']
    rules:
      max-files-in-dir: { max: 15 }

      naming-convention:
        "*.py": "snake_case"
        "*.sh": "snake_case"
        "*.bat": "snake_case"
        "**/": "snake_case"

  # Config: kebab-case
  - files: ['config/**']
    rules:
      naming-convention:
        "**/": "kebab-case"

  # Root level: Relaxed rules for tooling configs
  - files: ['.']
    rules:
      max-files-in-dir: { max: 40 }
      max-subdirs: { max: 20 }

# Ignored paths (build artifacts, caches, dependencies)
ignore:
  - .git
  - .cache
  - .venv
  - api_venv
  - node_modules
  - __pycache__
  - .pytest_cache
  - .mypy_cache
  - .ruff_cache
  - dist
  - build
  - "*.egg-info"
  - .idea
  - .vscode
  - data/downloads
  - data/models
  - data/databases
  - src/backend/logs
  - src/frontend/frontend.log
  - ci-logs
